services:
  # --- Banco de Dados ---
  db:
    image: postgres:16-alpine
    container_name: db-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # OK para dev, não para prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Para debug local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d eventos_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # --- API Gateway (Porteiro) ---
  gateway:
    image: nginx:1.25-alpine
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "80:80" # A porta principal do projeto
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - servico_usuarios
      - servico_eventos
      - servico_certificados
      - servico_notificacoes

  # --- Microsserviço de Usuários (Python) ---
  servico_usuarios:
    build: ./servico_usuarios
    container_name: ms-usuarios
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_usuarios/src:/app
      - ./servico_comum:/app/servico_comum
    expose:
      - "8000" # Porta interna (Uvicorn)
    depends_on:
      db:
        condition: service_healthy

  # --- Microsserviço de Eventos (Python) ---
  servico_eventos:
    build: ./servico_eventos
    container_name: ms-eventos
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_eventos/src:/app
      - ./servico_comum:/app/servico_comum
    expose:
      - "8000" # Porta interna
    depends_on:
      - db

  # --- Microsserviço de Certificados (Python) ---
  servico_certificados:
    build: ./servico_certificados
    container_name: ms-certificados
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_certificados/src:/app
      - ./servico_comum:/app/servico_comum
    expose:
      - "8000" # Porta interna
    depends_on:
      - db

  # --- Microsserviço de Notificações (Node.js) ---
  servico_notificacoes:
    build: ./servico_notificacoes
    container_name: ms-notificacoes
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_notificacoes/src:/app # Hot-reload para Node
      - /app/node_modules
    expose:
      - "8004" # Porta interna do Node
  
  # --- SEU NOVO SERVIÇO DE FRONTEND (PORTAL) ---
  portal-web:
    build:
      context: ./portal-web
      dockerfile: Dockerfile
    container_name: portal_web_c
    ports:
      - "3000:3000" # Acessível em localhost:3000
    volumes:
      - ./portal-web:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - gateway # O portal depende do gateway
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local