services:
  # --- Banco de Dados ---
  db:
    image: postgres:16-alpine
    container_name: db-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Para debug local

  # --- Microsserviço de Usuários (Python) ---
  servico_usuarios:
    build: ./servico_usuarios
    container_name: ms-usuarios
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_usuarios/src:/app # Hot-reload
    ports:
      - "8001:8000" # Acessível em localhost:8001
    depends_on:
      - db

  # --- Microsserviço de Eventos (Python) ---
  servico_eventos:
    build: ./servico_eventos
    container_name: ms-eventos
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_eventos/src:/app
    ports:
      - "8002:8000" # Acessível em localhost:8002
    depends_on:
      - db

  # --- Microsserviço de Certificados (Python) ---
  servico_certificados:
    build: ./servico_certificados
    container_name: ms-certificados
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_certificados/src:/app
    ports:
      - "8003:8000" # Acessível em localhost:8003
    depends_on:
      - db

  # --- Microsserviço de Notificações (Node.js) ---
  servico_notificacoes:
    build: ./servico_notificacoes
    container_name: ms-notificacoes
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./servico_notificacoes/src:/app # Hot-reload para Node
    ports:
      # Assumindo que seu app Node rode na porta 8004
      - "8004:8004" # Acessível em localhost:8004

  # --- SEU NOVO SERVIÇO DE FRONTEND (PORTAL) ---
  portal-web:
    build:
      context: ./portal-web
      dockerfile: Dockerfile
    container_name: portal_web_c
    ports:
      - "3000:3000" # Acessível em localhost:3000
    volumes:
      - ./portal-web:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      # Garante que o frontend suba depois das APIs
      - servico_usuarios
      - servico_eventos
      - servico_certificados
      - servico_notificacoes
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local